# Información del proyecto
sonar.projectKey=taller-api-2
sonar.projectName=Taller API 2
sonar.projectVersion=1.0

# Rutas de código fuente y binarios
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# Configuración de Java
sonar.java.source=17
sonar.java.target=17

# Exclusiones
sonar.exclusions=**/dto/**,**/config/**,**/TallerApi2Application.java

# Cobertura de código
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Encoding
sonar.sourceEncoding=UTF-8