# Configuracion del servidor y entorno

# Desactivar integracion automatica con docker-compose de Spring Boot
spring.docker.compose.enabled=false

# Puerto donde correra el backend (ahora en 8080)
server.port=8080


# Configuracion de base de datos (PostgreSQL)

# URL de conexion (usa variables de entorno DB_URL por si trabajan en contenedores)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tallerdb}

# Credenciales de base de datos
spring.datasource.username=${DB_USER:talleruser}
spring.datasource.password=${DB_PASSWORD:tallerpass}

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Estrategia de JPA: validate solo valida que las entidades coincidan con las tablas
spring.jpa.hibernate.ddl-auto=update

# Mostrar queries en logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.flyway.enabled=false

# Seguridad y JWT (Keycloak)

# Issuer y JWK set para que el resource-server valide los tokens JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/taller
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8082/realms/taller/protocol/openid-connect/certs

# Configuracion de Keycloak para auth de usuarios
keycloak.auth-server-url=http://localhost:8082
keycloak.realm=taller
keycloak.resource=taller-api
keycloak.credentials.secret=jx34gvJ7Vo9UwxLwsbLa1K3C58ZbjrLh

# Configuracion de Keycloak Admin API (para crear/editar usuarios desde backend)
keycloak.admin.client-id=taller-api-admin
keycloak.admin.client-secret=g1IP83yywb0qGcpP2RJ93wKXTcK4CuXH
keycloak.admin.url=http://localhost:8082
keycloak.admin.realm=taller
app.keycloak.enabled=false

# Configuracion de RabbitMQ

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Exchange principal para los eventos de la app
app.rabbitmq.exchange=app.events

# Evento: creacion de usuario
app.rabbitmq.usuarios.queue=usuarios.events
app.rabbitmq.usuarios.routingKey=usuarios.created

# Evento: inicio de sesion
app.rabbitmq.sesiones.queue=sesiones.events
app.rabbitmq.sesiones.routingKey=sesiones.iniciada

# Evento: password
app.rabbitmq.password.queue=password.events
app.rabbitmq.password.routingKey=password.reset

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
management.health.defaults.enabled=true


# Prometheus metrics - (micrometer) - nada extra necesario, micrometer ya expondra /actuator/prometheus
# Opcional: cambiar puerto del actuator (dejaremos en mismo puerto 8080).

# Metadata de version (util en health)
app.version=${project.version:0.0.1-SNAPSHOT}
